# Generated by Django 2.1.4 on 2019-03-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=1200)),
                ('state', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=False)),
                ('offline', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('login', models.CharField(max_length=120)),
                ('psw', models.CharField(max_length=88)),
                ('tmp_url', models.CharField(max_length=25)),
                ('logged_in_cookie', models.CharField(max_length=120)),
            ],
        ),
    ]
